CREATE TYPE user_role AS ENUM ('ADMIN', 'USER');
CREATE TYPE sale_status AS ENUM ('OPEN', 'FINISHED', 'CANCELED');
CREATE TYPE payment_type AS ENUM ('MONEY', 'PIX', 'DEBIT_CARD', 'CREDIT_CARD', 'VOUCHER', 'TICKET');
CREATE TYPE spun_status AS ENUM ('OPEN', 'PAY', 'LATE');
CREATE TYPE movement_type AS ENUM ('ENTRY', 'EXIT_SALE', 'ADJUSTMENT', 'LOSS');